---
interval: 5s
time_series:
  - series: kas_fleet_manager_kafka_requests_status_since_last_set{cluster_id="1jp6kdr7k0sjbe5adck2prjur8f39378",id="cdh36943c37idfspotqg",status="ready"}
    progression: "0+(rnd)x50"
